### PR TITLE
Add parallel compilation for faster builds

### PR DESCRIPTION
**Pull request by maseabunikie**

### CODE REVIEW

**Review by joonas-fi — APPROVED** [review]
LGTM, good improvement :+1:

**Review by mehmetkillioglu — APPROVED** [review]
Great addition to speed up local builds! Maybe we can add the workflow dispatch to this PR also.

**Comment by maseabunikie** [comment]
@mehmetkillioglu I am planning to add it to this PR and have a small rehearsal with it before I add PKCS#11 changes which is bigger change.

**Comment by maseabunikie** [comment]
@joonas-fi I have removed fakeroot after doing testing to build fog-bumper and navigation locally. It works.

**Comment by joonas-fi** [comment]
@maseabunikie awesome, thanks for doing it so quick :clap:

**Comment by joonas-fi** [comment]
For your consideration: it might be possible to remove fakeroot package as well: https://github.com/tiiuae/fog-ros-baseimage/blob/a4c0d819d579efc47078e336c3a5d45244b99abe/Dockerfile.builder#L30

**Review by jnippula — APPROVED** [review]

**Pull request merged**
